spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/template?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 200
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 300
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 2000
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sxbdjw.bdjwkingbaseapi.model
